import {
  ChurnTrendPoint,
  DashboardStat,
  FrameworkKpi,
  RecentRun,
  SectorHealth,
} from "@/lib/types";

export const dashboardStats: DashboardStat[] = [
  {
    id: "total-predictions",
    label: "Total Predictions",
    value: "48,203",
    delta: "+12.4%",
    deltaDirection: "up",
    description: "Last 30 days across all sectors",
  },
  {
    id: "avg-churn-rate",
    label: "Avg. Churn Rate",
    value: "23.6%",
    delta: "-1.8%",
    deltaDirection: "down",
    description: "Blended across active sector models",
  },
  {
    id: "concept-confidence",
    label: "Avg. Concept Confidence",
    value: "71.2%",
    delta: "+3.1%",
    deltaDirection: "up",
    description: "Business concept reconstruction quality",
  },
  {
    id: "routing-green",
    label: "Green Routing Rate",
    value: "84.9%",
    delta: "+0.6%",
    deltaDirection: "up",
    description: "Runs routed to full sector models",
  },
];

export const frameworkKpis: FrameworkKpi[] = [
  {
    id: "coverage-intelligence",
    label: "Coverage Intelligence",
    value: "78.4%",
    description: "Required feature surface available",
    trend: "up",
    trendValue: "+2.1%",
  },
  {
    id: "concept-confidence",
    label: "Concept Confidence",
    value: "46.0%",
    description: "Business concepts reconstructed",
    trend: "up",
    trendValue: "+3.1%",
  },
  {
    id: "prediction-reliability",
    label: "Prediction Reliability",
    value: "91%",
    description: "Quality Gate pass rate",
    trend: "flat",
    trendValue: "0.0%",
  },
  {
    id: "decision-readiness",
    label: "Decision Readiness",
    value: "Green",
    description: "Latest run routing tier",
  },
  {
    id: "business-health",
    label: "Business Health",
    value: "Stable",
    description: "Blended churn trend across sectors",
    trend: "down",
    trendValue: "-1.8%",
  },
  {
    id: "routing-decision",
    label: "Routing Decision",
    value: "Full Sector Model",
    description: "Adaptive Routing output for latest run",
  },
  {
    id: "selected-model",
    label: "Selected Model",
    value: "telecom_best.pkl",
    description: "Sector-specific trained artifact",
  },
  {
    id: "rows-processed",
    label: "Rows Processed",
    value: "48,203",
    description: "Last 30 days across all sectors",
    trend: "up",
    trendValue: "+12.4%",
  },
  {
    id: "industry",
    label: "Industry",
    value: "Telecom",
    description: "Most recently processed sector",
  },
];

export const sectorHealth: SectorHealth[] = [
  {
    sector: "telecom",
    label: "Telecom",
    churnRate: 26.4,
    totalRecords: 18240,
    avgConceptConfidence: 74.5,
    status: "complete",
    lastRunAt: "2026-07-03T09:12:00Z",
  },
  {
    sector: "banking",
    label: "Banking",
    churnRate: 19.8,
    totalRecords: 14310,
    avgConceptConfidence: 81.2,
    status: "complete",
    lastRunAt: "2026-07-03T07:44:00Z",
  },
  {
    sector: "healthcare",
    label: "Healthcare",
    churnRate: 15.1,
    totalRecords: 9870,
    avgConceptConfidence: 63.9,
    status: "warning",
    lastRunAt: "2026-07-02T21:05:00Z",
  },
  {
    sector: "ecommerce",
    label: "E-commerce",
    churnRate: 32.9,
    totalRecords: 5783,
    avgConceptConfidence: 68.4,
    status: "complete",
    lastRunAt: "2026-07-03T05:30:00Z",
  },
];

export const churnTrend: ChurnTrendPoint[] = [
  { date: "Jun 27", telecom: 25.1, banking: 18.9, healthcare: 14.2, ecommerce: 30.4 },
  { date: "Jun 28", telecom: 25.8, banking: 19.2, healthcare: 14.6, ecommerce: 31.1 },
  { date: "Jun 29", telecom: 24.9, banking: 19.5, healthcare: 15.0, ecommerce: 33.2 },
  { date: "Jun 30", telecom: 26.2, banking: 20.1, healthcare: 14.8, ecommerce: 32.6 },
  { date: "Jul 01", telecom: 27.0, banking: 19.7, healthcare: 15.3, ecommerce: 31.9 },
  { date: "Jul 02", telecom: 26.6, banking: 19.4, healthcare: 15.4, ecommerce: 32.1 },
  { date: "Jul 03", telecom: 26.4, banking: 19.8, healthcare: 15.1, ecommerce: 32.9 },
];

export const recentRuns: RecentRun[] = [
  {
    id: "run-1042",
    sector: "telecom",
    mode: "Auto",
    routingTier: "Green",
    recordCount: 1204,
    churnDetected: 318,
    submittedAt: "2026-07-03T09:12:00Z",
    status: "complete",
  },
  {
    id: "run-1041",
    sector: "banking",
    mode: "Sector",
    routingTier: "Green",
    recordCount: 860,
    churnDetected: 171,
    submittedAt: "2026-07-03T07:44:00Z",
    status: "complete",
  },
  {
    id: "run-1040",
    sector: "healthcare",
    mode: "Universal",
    routingTier: "Yellow",
    recordCount: 512,
    churnDetected: 77,
    submittedAt: "2026-07-02T21:05:00Z",
    status: "warning",
  },
  {
    id: "run-1039",
    sector: "ecommerce",
    mode: "Auto",
    routingTier: "Green",
    recordCount: 943,
    churnDetected: 310,
    submittedAt: "2026-07-03T05:30:00Z",
    status: "complete",
  },
  {
    id: "run-1038",
    sector: "telecom",
    mode: "Universal",
    routingTier: "Red",
    recordCount: 128,
    churnDetected: 0,
    submittedAt: "2026-07-02T18:02:00Z",
    status: "failed",
  },
];
