from __future__ import annotations
from enum import Enum


class ExecutionMode(str, Enum):
    STRICT_PRODUCTION = "STRICT_PRODUCTION"
    SHADOW = "SHADOW"
    DIAGNOSTIC = "DIAGNOSTIC"
    RESEARCH = "RESEARCH"
    OFFLINE_PROFILE_ONLY = "OFFLINE_PROFILE_ONLY"


class EvidenceFamily(str, Enum):
    LEXICAL = "LEXICAL"; ABBREVIATION = "ABBREVIATION"; NAMING = "NAMING"; UNIT = "UNIT"
    DATATYPE = "DATATYPE"; STATISTICAL = "STATISTICAL"; CARDINALITY = "CARDINALITY"
    NULL_PATTERN = "NULL_PATTERN"; TEMPORAL = "TEMPORAL"; IDENTIFIER = "IDENTIFIER"
    RELATIONAL = "RELATIONAL"; DATASET_CONTEXT = "DATASET_CONTEXT"; SECTOR_CONTEXT = "SECTOR_CONTEXT"
    BUSINESS_RULE = "BUSINESS_RULE"; CATALOG_METADATA = "CATALOG_METADATA"


class ValidationOutcome(str, Enum):
    CONFIRMED = "CONFIRMED"; SUPPORTED = "SUPPORTED"; NEUTRAL = "NEUTRAL"
    CONTRADICTED = "CONTRADICTED"; NOT_APPLICABLE = "NOT_APPLICABLE"


class ResolutionStatus(str, Enum):
    DETERMINISTIC_EXACT = "DETERMINISTIC_EXACT"
    DETERMINISTIC_REGEX = "DETERMINISTIC_REGEX"
    SEMANTIC_ACCEPTED = "SEMANTIC_ACCEPTED"
    SEMANTIC_REVIEW_REQUIRED = "SEMANTIC_REVIEW_REQUIRED"
    SEMANTIC_ABSTAINED = "SEMANTIC_ABSTAINED"
    UNRESOLVED = "UNRESOLVED"


class AbstentionStatus(str, Enum):
    ACCEPTED = "ACCEPTED"; REVIEW_REQUIRED = "REVIEW_REQUIRED"; ABSTAINED = "ABSTAINED"


class Severity(str, Enum):
    INFO = "INFO"; LOW = "LOW"; MEDIUM = "MEDIUM"; HIGH = "HIGH"; CRITICAL = "CRITICAL"
